[package]
name = "oxide"
version = "0.1.0"
authors = ["Justin Sacbibit <jsacbibit@gmail.com>"]

[dependencies]
clap = "*"
flate2 = "0.2"
log = "0.3"
regex = "0.1.41"
rust-crypto = "0.2"
rustc-serialize = "0.3.16"
time = "0.1"

